"""AgentState TypedDict for LangGraph MCP Security Control Plane agents."""

from __future__ import annotations

from typing import Annotated, Any, Optional

from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AgentState(TypedDict, total=False):
    """Shared state schema for all LangGraph agents in the MCP Security Control Plane.

    Fields are populated and mutated by graph nodes as execution progresses.
    All fields except ``messages``, ``agent_id``, and ``task`` are optional
    at graph entry — nodes must handle absent keys gracefully.
    """

    # ── Core conversation / identity ─────────────────────────────────────────
    messages: Annotated[list[Any], add_messages]
    """LangChain message list, reduced by ``add_messages`` on each update.
    Carries the full conversation history including tool call records."""

    agent_id: str
    """Registry identifier of the running agent, e.g. ``mcp-auditor``."""

    task: str
    """Free-text description of the current task, injected at graph entry."""

    # ── RAG / retrieval ───────────────────────────────────────────────────────
    retrieved_docs: list[dict[str, Any]]
    """Documents retrieved from the RAG pipeline.
    Each element: ``{id, content, score, source, metadata}``."""

    # ── Audit data ────────────────────────────────────────────────────────────
    tool_call_logs: list[dict[str, Any]]
    """Raw tool call log records fetched from the audit database.
    Each element mirrors the ``audit_log`` table schema."""

    # ── Analysis results ──────────────────────────────────────────────────────
    violations: list[dict[str, Any]]
    """Detected policy / scope violations.
    Each element: ``{tool, agent_id, timestamp, severity, code, description,
    policy_citation, raw_log_ref}``."""

    # ── Output ────────────────────────────────────────────────────────────────
    compliance_report: Optional[str]
    """Markdown-formatted compliance report generated by ``generate_report``
    node. ``None`` until that node has executed."""

    # ── Iteration control ─────────────────────────────────────────────────────
    iteration_count: int
    """Number of analysis-loop iterations completed so far. Starts at 0."""

    max_iterations: int
    """Hard ceiling on analysis-loop iterations, sourced from agent profile."""

    # ── Error handling ────────────────────────────────────────────────────────
    error: Optional[str]
    """Set by any node that encounters a non-retriable error. Presence causes
    the graph router to exit immediately."""
